version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: matheusmaia_dev
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - msmaia_postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  msmaia_postgres: